//! Offline sample data for `glab-feed --demo`. No config, network, or disk.
use chrono::{Duration, Utc};

use crate::app::{App, RepoState};
use crate::config::RepoCfg;
use crate::gitlab::{CiStatus, MergeRequest, UpdateActivity};
use crate::notifications::NotificationStore;

pub fn app() -> App {
    let repos = vec![
        repo("frontend", "group/frontend"),
        repo("ui-kit", "group/ui-kit"),
        repo("api", "group/api"),
    ];
    let mut app = App::new("git.example.com".into(), repos, "alex".into(), false, false);
    app.fetching = false;
    app.notification_store = NotificationStore::default();
    app.repo_states = vec![
        loaded(frontend_mrs()),
        loaded(ui_kit_mrs()),
        loaded(api_mrs()),
    ];
    app.table_state.select(Some(0));
    app
}

fn repo(name: &str, path: &str) -> RepoCfg {
    RepoCfg {
        name: Some(name.into()),
        path: path.into(),
    }
}

fn loaded(mrs: Vec<MergeRequest>) -> RepoState {
    RepoState {
        mrs,
        error: None,
        loaded: true,
    }
}

fn mr(
    iid: &str,
    title: &str,
    name: &str,
    username: &str,
    draft: bool,
    approved: bool,
    conflicts: bool,
    notes: u32,
    last_note: Option<&str>,
    note_hours: i64,
    ci: CiStatus,
    age_days: i64,
    updated_mins: i64,
    activity: Option<(UpdateActivity, &str)>,
) -> MergeRequest {
    let now = Utc::now();
    MergeRequest {
        iid: iid.into(),
        title: title.into(),
        web_url: format!("https://git.example.com/group/frontend/-/merge_requests/{iid}"),
        author_name: name.into(),
        author_username: username.into(),
        approved_by: if approved {
            vec!["sam".into()]
        } else {
            Vec::new()
        },
        approved,
        draft,
        has_conflicts: conflicts,
        notes_count: notes,
        last_note_author: last_note.map(str::to_string),
        last_note_at: last_note.map(|_| now - Duration::hours(note_hours)),
        ci,
        created_at: now - Duration::days(age_days),
        updated_at: now - Duration::minutes(updated_mins),
        source_branch: format!("feature-{iid}"),
        last_update: activity.map(|(kind, user)| (kind, user.to_string())),
    }
}

fn frontend_mrs() -> Vec<MergeRequest> {
    vec![
        mr(
            "1284",
            "Add keyboard shortcut for copying the link",
            "Alex Rivera",
            "alex",
            false,
            false,
            false,
            3,
            Some("sam"),
            4,
            CiStatus::Pass,
            2,
            18,
            Some((UpdateActivity::Note, "sam")),
        ),
        mr(
            "1271",
            "Fix empty state when the list is filtered",
            "Sam Okonkwo",
            "sam",
            false,
            true,
            false,
            1,
            Some("jordan"),
            5,
            CiStatus::Pass,
            4,
            40,
            Some((UpdateActivity::Build, "sam")),
        ),
        mr(
            "1266",
            "Show a badge when the branch has conflicts",
            "Jordan Lee",
            "jordan",
            false,
            false,
            true,
            6,
            Some("alex"),
            20,
            CiStatus::Fail,
            5,
            90,
            Some((UpdateActivity::Push, "jordan")),
        ),
        mr(
            "1258",
            "Draft: rename the config field",
            "Riley Chen",
            "riley",
            true,
            false,
            false,
            0,
            None,
            0,
            CiStatus::None,
            6,
            180,
            Some((UpdateActivity::Push, "riley")),
        ),
        mr(
            "1244",
            "Quiet noisy retry logs",
            "Morgan Blake",
            "morgan",
            false,
            false,
            false,
            2,
            Some("alex"),
            26,
            CiStatus::InProgress,
            8,
            15,
            Some((UpdateActivity::Build, "morgan")),
        ),
        mr(
            "1230",
            "Add a countdown to the next refresh",
            "Alex Rivera",
            "alex",
            false,
            true,
            false,
            4,
            Some("riley"),
            30,
            CiStatus::Pass,
            9,
            200,
            Some((UpdateActivity::Note, "riley")),
        ),
        mr(
            "1219",
            "Document the first-run setup",
            "Sam Okonkwo",
            "sam",
            false,
            false,
            false,
            0,
            None,
            0,
            CiStatus::Cancelled,
            11,
            300,
            Some((UpdateActivity::Push, "sam")),
        ),
        mr(
            "1202",
            "Extract the table header into a helper",
            "Jordan Lee",
            "jordan",
            false,
            false,
            false,
            8,
            Some("morgan"),
            10,
            CiStatus::Pass,
            12,
            50,
            Some((UpdateActivity::Note, "morgan")),
        ),
        mr(
            "1188",
            "Bump the CI image to the latest stable",
            "Riley Chen",
            "riley",
            false,
            false,
            false,
            1,
            Some("sam"),
            48,
            CiStatus::Fail,
            14,
            400,
            Some((UpdateActivity::Build, "riley")),
        ),
        mr(
            "1175",
            "Convert status colors to a shared palette",
            "Morgan Blake",
            "morgan",
            true,
            false,
            false,
            0,
            None,
            0,
            CiStatus::Pass,
            16,
            600,
            Some((UpdateActivity::Push, "morgan")),
        ),
        mr(
            "1160",
            "Add CSV export for the usage page",
            "Alex Rivera",
            "alex",
            false,
            false,
            false,
            5,
            Some("jordan"),
            8,
            CiStatus::Pass,
            18,
            70,
            Some((UpdateActivity::Note, "jordan")),
        ),
        mr(
            "1142",
            "Fix the permission check on project settings",
            "Sam Okonkwo",
            "sam",
            false,
            true,
            false,
            2,
            Some("alex"),
            72,
            CiStatus::Pass,
            21,
            800,
            Some((UpdateActivity::Note, "alex")),
        ),
    ]
}

fn ui_kit_mrs() -> Vec<MergeRequest> {
    vec![
        mr(
            "88",
            "Add a focus ring to icon buttons",
            "Jordan Lee",
            "jordan",
            false,
            false,
            false,
            2,
            Some("riley"),
            3,
            CiStatus::Pass,
            1,
            25,
            Some((UpdateActivity::Note, "riley")),
        ),
        mr(
            "81",
            "Draft: split the token file",
            "Riley Chen",
            "riley",
            true,
            false,
            false,
            0,
            None,
            0,
            CiStatus::InProgress,
            3,
            40,
            Some((UpdateActivity::Build, "riley")),
        ),
        mr(
            "74",
            "Fix contrast on the secondary text",
            "Morgan Blake",
            "morgan",
            false,
            true,
            false,
            1,
            Some("alex"),
            12,
            CiStatus::Pass,
            7,
            120,
            Some((UpdateActivity::Note, "alex")),
        ),
        mr(
            "69",
            "Export the spacing scale",
            "Alex Rivera",
            "alex",
            false,
            false,
            false,
            0,
            None,
            0,
            CiStatus::None,
            10,
            240,
            Some((UpdateActivity::Push, "alex")),
        ),
    ]
}

fn api_mrs() -> Vec<MergeRequest> {
    vec![
        mr(
            "410",
            "Paginate the activity endpoint",
            "Sam Okonkwo",
            "sam",
            false,
            false,
            false,
            4,
            Some("morgan"),
            6,
            CiStatus::Pass,
            2,
            35,
            Some((UpdateActivity::Note, "morgan")),
        ),
        mr(
            "402",
            "Return a clearer error on a bad token",
            "Morgan Blake",
            "morgan",
            false,
            false,
            true,
            1,
            Some("sam"),
            9,
            CiStatus::Fail,
            5,
            55,
            Some((UpdateActivity::Push, "morgan")),
        ),
        mr(
            "390",
            "Draft: drop the unused health field",
            "Jordan Lee",
            "jordan",
            true,
            false,
            false,
            0,
            None,
            0,
            CiStatus::Cancelled,
            9,
            500,
            Some((UpdateActivity::Build, "jordan")),
        ),
    ]
}
